services:

  ## Kafka and Zookeeper setup
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT:-2181}
      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME:-2000}
    networks:
      - data-network

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_HOST_PORT:-9092}:9092"
    env_file:
      - .env
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID:-1}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT:-zookeeper:2181}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:-PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT}
      - KAFKA_INTER_BROKER_LISTENER_NAME=${KAFKA_INTER_BROKER_LISTENER_NAME:-PLAINTEXT}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-1}
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data-network

  kafka-ui:
    image: kafbat/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "${KAFKA_UI_PORT:-8085}:8080"
    env_file:
      - .env
    environment:
      - DYNAMIC_CONFIG_ENABLED='true'
      - KAFKA_CLUSTERS_0_NAME=${KAFKA_UI_CLUSTER_NAME:-local}
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
    networks:
      - data-network

  ## Application services
  mta-producer:
    build:
      dockerfile: ./docker/producer.Dockerfile
    container_name: mta-producer
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - data-network

  ## MinIO setup for S3-compatible storage
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9095}:9001"
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - data-network

  mc:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - data-network
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio ${S3_ENDPOINT:-http://minio:9000} ${MINIO_ROOT_USER:-admin} ${MINIO_ROOT_PASSWORD}) do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb myminio/mta-bronze;
      /usr/bin/mc mb myminio/mta-silver;
      /usr/bin/mc mb myminio/mta-gold;
      exit 0;
      "

  ## Spark setup
  spark-master:
    build:
      dockerfile: ./docker/spark.Dockerfile
    container_name: spark-master
    env_file:
      - .env
    ports:
      - "${SPARK_MASTER_UI_PORT:-8080}:8080"
      - "${SPARK_MASTER_PORT:-7077}:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HOME=/tmp
      - SPARK_USER_HOME_DIR=/opt/spark/work-dir
      - SPARK_DAEMON_JAVA_OPTS="-Divy.home=/tmp/.ivy2"
      - S3_ENDPOINT=${S3_ENDPOINT:-http://minio:9000}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-admin}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    command: >
      /bin/sh -c "mkdir -p /tmp/.ivy2 && chmod -R 777 /tmp/.ivy2 && /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    networks:
      - data-network

  spark-worker:
    build:
      dockerfile: ./docker/spark.Dockerfile
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:${SPARK_MASTER_PORT:-7077}
      - "JAVA_TOOL_OPTIONS=-Duser.home=/tmp -Djava.io.tmpdir=/tmp"
      - SPARK_DRIVER_HOST=spark-master
      - S3_ENDPOINT=${S3_ENDPOINT:-http://minio:9000}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-admin}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES:-4}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY:-4g}
      - SPARK_SHUFFLE_SERVICE_ENABLED=true
      - SPARK_SCHEDULER_MODE=FAIR
    volumes:
    - .:/opt/spark/work-dir
    command: >
      /bin/sh -c "mkdir -p /tmp/.ivy2 && chmod -R 777 /tmp/.ivy2 && /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:${SPARK_MASTER_PORT:-7077}"
    depends_on:
      - spark-master
    networks:
      - data-network

    ## Airflow setup for orchestration
    ## As per documentation, docker compose is not recommended for PROD environment
    ## More at: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html
  postgres:
    image: postgres:14.22-alpine3.22
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
    networks:
      - data-network

  airflow:
    build:
      dockerfile: ./docker/airflow.Dockerfile
    container_name: airflow
    depends_on:
      - spark-master
      - postgres
    environment:
          - AIRFLOW__CORE__EXECUTOR=LocalExecutor
          - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW_DATABASE_SQL_CONN_STRING}
          - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
          - AIRFLOW__CORE__LOAD_EXAMPLES=False
          - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
          - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/src/dags
          - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:${SPARK_MASTER_PORT:-7077}
          - _AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_USERNAME:-admin}
          - _AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_PASSWORD}
          - SPARK_LOCAL_IP=airflow
          - SPARK_DRIVER_HOST=${POSTGRES_DB:-airflow}
    ports:
      - "${AIRFLOW_PORT:-8086}:8080"
    command: standalone # Standalone mode only for local testing
    networks:
      - data-network

networks:
  data-network:
    driver: bridge